name: Java CI with Maven and Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Initialize CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: java

    - name: Build and run tests with Maven
      run: ./mvnw clean verify

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
